CREATE TABLE `devices` (
 `deviceId` int NOT NULL AUTO_INCREMENT,
 `userId` int NOT NULL,
 `singleDeviceMode` bit NOT NULL,
 `uploadFrequencyMins` int NOT NULL,
 `emailAddress` nvarchar(512) NULL,
 `plant1Name` nvarchar(512) NULL,
 `plant2Name` nvarchar(512) NULL,

 `temp1Enable` bit NOT NULL,
 `temp1LampTempShutoff` bit not null,
 `temp1LampMaxTemp` float not null,
 `temp1HiTempAlarm` bit not null,
 `temp1HiTempEmail` bit not null,
 `temp1HiTemp` float not null,
 `temp2Enable` bit NOT NULL,
 `temp2LampTempShutoff` bit not null,
 `temp2LampMaxTemp` float not null,
 `temp2HiTempAlarm` bit not null,
 `temp2HiTempEmail` bit not null,
 `temp2HiTemp` float not null,

 `lamp1Enable` bit not null,
 `lamp1HeaterMode` bit not null,
 `lamp1HeaterTemp` float not null,
 `lamp1StartTimeVeg` time not null,
 `lamp1EndTimeVeg` time not null,
 `lamp1FlowerMode` bit not null,
 `lamp1StartTimeFlower` time not null,
 `lamp1EndTimeFlower` time not null,
 `lamp1InvertRelayLogic` bit not null,
 `lamp2Enable` bit not null,
 `lamp2HeaterMode` bit not null,
 `lamp2HeaterTemp` float not null,
 `lamp2StartTimeVeg` time not null,
 `lamp2EndTimeVeg` time not null,
 `lamp2FlowerMode` bit not null,
 `lamp2StartTimeFlower` time not null,
 `lamp2EndTimeFlower` time not null,
 `lamp2InvertRelayLogic` bit not null,

 `pump1Enable` bit not null,
 `pump1FlowMode` bit not null,
 `pump1FlowMl` int not null,
 `pump1LowFlowEmail` bit not null,
 `pump1LowFlowAlarm` bit not null,
 `pump1DurationSecs` int not null,
 `pump1FrequencyMins` int not null,
 `pump1InvertRelayLogic` bit not null,
 `pump2Enable` bit not null,
 `pump2FlowMode` bit not null,
 `pump2FlowMl` int not null,
 `pump2LowFlowEmail` bit not null,
 `pump2LowFlowAlarm` bit not null,
 `pump2DurationSecs` int not null,
 `pump2FrequencyMins` int not null,
 `pump2InvertRelayLogic` bit not null,

 `float1Enable` bit not null,
 `float1Alarm` bit not null,
 `float1PumpShutoff` bit not null,
 `float1InvertSensorLogic` bit not null,
 `float2Enable` bit not null,
 `float2Alarm` bit not null,
 `float2PumpShutoff` bit not null,
 `float2InvertSensorLogic` bit not null,

 `flow1Enable` bit not null,
 `flow2Enable` bit not null

 PRIMARY KEY (`deviceId`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1